### ISSUE TITLE
iConomy resetting balances?

### ISSUE THREAD

**Issue by EvilKnievelGreb** [iConomy/Core#182]
Hi im having a problem with iConomy resetting balances every so often at random times, i dont see any errors to give me any information as to why this is happening, im using bukkit 1.2.5 R1 and we're currently running iconomy  6.0.8. As far as im aware we have it linked to our mySQL DB.

Is there any known compatibility issues with other plugins? We're mainly using Essentials,mcMMO,Chestshop,World Portal, Minequery, PEX , Logblock , cart dispenser, NoLagg, Vault, Quarantine, found diamonds, lockette, border guard and dynmap..also have a few others running.

Any help would be appreciated, really cant seem to solve this.

**Comment by JustinBenedick** [comment]
I have had the same issue.

**Comment by Fureniku** [comment]
Yeah I'm also getting the issue. Considering the databases couldn't be ported from 5.0 already, and now this, I'm seriously thinking of switching plugins. It'd be a shame - I've used iConomy since I started my server over a year ago (back in hMod) - but at the end of the day my server relies 100% on the economy - ONE wipe is not acceptible to me (especially with a ticket that never got a response) but I've now had 3.

If you can fix it, I'd LOVE to keep this plugin... but in all fairness its not something I can wait a month for a fix for...

**Comment by EvilKnievelGreb** [comment]
And again this has happened! Can somebody PLEASE fix this.

**Comment by JustinBenedick** [comment]
I did try to solve the issue by using a sql server but it was too slow. I ended up switching to the BOSE economy plugin.

**Comment by EvilKnievelGreb** [comment]
Yup same, ive switched plugins also so need to help anymore....not like you were going to anyway.
