### ISSUE TITLE
[REQ] Change balances column from DECIMAL to INTEGER

### ISSUE THREAD

**Issue by ShadowDrakken** [iConomy/Core#2]
SQLite doesn't officially support DECIMAL(), it accepts it, but it casts it to INTEGER instead, so we may want to consider a change in how we handle decimals

possibly like a cash register and have iConomy shift the decimal itself
eg. inputting 2000 = $20.00 on a cash register

This will let us continue to support decimal values, but at the same time being more compatible.

This would all be behind the scenes stuff, players would still see and use decimals, it just would be stored as integers in the database.

The reason for this is because non-Java implementations of SQLite choke on DECIMAL fields and are unable to open the database.

**Comment by nijikokun** [comment]
Inputting 2000 should be 2,000 as opposed to 20.00; SQLite does officially support it, it's in SQLite3.
Shifting shouldn't need to be done, nor is any of this necessary.

**Comment by ShadowDrakken** [comment]
I think you're misunderstanding still... SQLite accepts DECIMAL, but it's considered an optionally supported datatype that SQLite libraries are free to leave out
you're also completely misunderstanding what I'm saying about using 2000 to mean 20.00, but whatever

**Comment by nijikokun** [comment]
No, I understand perfectly fine, I worked registers for a very long time. It's concept is that you start at the second zero and go forward. It's a flawed concept and only useful if visually seen; Also, no SQLite does officially support decimal it is however that SQLite is a Type Affinity database:

<pre>In order to maximize compatibility between SQLite and other database engines, SQLite supports the concept of "type affinity" on columns. The type affinity of a column is the recommended type for data stored in that column. The important idea here is that the type is recommended, not required. Any column can still store any type of data. It is just that some columns, given the choice, will prefer to use one storage class over another. The preferred storage class for a column is called its "affinity".</pre>


As quoted from their page on types and supported types.

Whatever library you are using to open the database, and or read it does not support Decimal, but SQLite surely does. Do not give false information.
