### ISSUE TITLE
/money top

### ISSUE THREAD

**Issue by SirJohnTheMaster** [iConomy/Core#216]
crashes the server still.

**Comment by x3roenie** [comment]
I need this fixed too, before it worked and showed the list.
But now it shows a empty list and crashes the server.

**Comment by Jason123** [comment]
for me it doesn't crash, but does spit out errors. I really need this working, so is there any way to fix? This is what happens:
22.06 22:35:06 [Server] INFO ... 7 more
22.06 22:35:06 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:40)
22.06 22:35:06 [Server] INFO at com.iCo6.iConomy.onCommand(iConomy.java:417)
22.06 22:35:06 [Server] INFO at com.iCo6.handlers.Top.perform(Top.java:33)
22.06 22:35:06 [Server] INFO at com.iCo6.system.Accounts.getTopAccounts(Accounts.java:21)
22.06 22:35:06 [Server] INFO at com.iCo6.system.Queried.topAccounts(Queried.java:190)
22.06 22:35:06 [Server] INFO at java.util.Collections.sort(Collections.java:217)
22.06 22:35:06 [Server] INFO at java.util.Arrays.sort(Arrays.java:659)
22.06 22:35:06 [Server] INFO at java.util.TimSort.sort(TimSort.java:173)
22.06 22:35:06 [Server] INFO at java.util.TimSort.sort(TimSort.java:214)
22.06 22:35:06 [Server] INFO at java.util.TimSort.mergeCollapse(TimSort.java:410)
22.06 22:35:06 [Server] INFO at java.util.TimSort.mergeAt(TimSort.java:483)
22.06 22:35:06 [Server] INFO at java.util.TimSort.mergeLo(TimSort.java:747)
22.06 22:35:06 [Server] INFO Caused by: java.lang.IllegalArgumentException: Comparison method violates its general contract!
22.06 22:35:06 [Server] INFO at net.minecraft.server.ThreadServerApplication.run(SourceFile:492)
22.06 22:35:06 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:459)
22.06 22:35:06 [Server] INFO at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:581)
22.06 22:35:06 [Server] INFO at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:612)
22.06 22:35:06 [Server] INFO at org.bukkit.craftbukkit.CraftServer.dispatchServerCommand(CraftServer.java:475)
22.06 22:35:06 [Server] INFO at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:479)
22.06 22:35:06 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:166)
22.06 22:35:06 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:42)
22.06 22:35:06 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'money' in plugin iConomy v7.0
22.06 22:35:06 [Server] WARNING Unexpected exception while parsing console command
22.06 22:35:06 [Server] INFO -----[ Wealthiest Accounts ]-----
